name: Build and Push Docker Image

on:
  push:
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: calavelas/epam-demo
          tags: type=sha,prefix=,format=long

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src # Set the build context to the src directory
          push: true
          tags: ${{ steps.meta.outputs.tags }}

