name: Build and Push Docker Image and Update Docker Compose

on:
  push:
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Get commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
        
      - name: Debug SHORT_SHA
        run: echo "SHORT_SHA is ${{ env.SHORT_SHA }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src # Set the build context to the src directory
          file: ./src/Dockerfile
          push: true
          tags: calavelas/epam-demo:${{ env.SHORT_SHA }}

  update-docker-compose:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Update image tag in Docker Compose file
        run: |
          SHORT_SHA=${{ needs.build-and-push.outputs.short_sha }}
          sed -i "s|calavelas/epam-demo:1.0.0|calavelas/epam-demo:$SHORT_SHA|g" deployment/docker-compose.yaml
          
      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add deployment/docker-compose.yaml
          git commit -m "Update Docker Compose with new image tag ${{ needs.build-and-push.outputs.short_sha }}" || exit 0
          git push
